tests: fix pings to IPv6 addresses for the new tun address

diff --git a/tests/radius-test b/tests/radius-test
--- a/tests/radius-test
+++ b/tests/radius-test
@@ -80,12 +80,12 @@ if test $? != 0;then
 	stop
 fi
 
-#ping6 -w 5 fd91:6d87:7341:db6a::
-#if test $? != 0;then
-#	kill $PID
-#	echo "Cannot ping the IPv6 of ocserv"
-#	stop
-#fi
+ping6 -w 5 fd91:6d87:7341:db6a::1
+if test $? != 0;then
+	kill $PID
+	echo "Cannot ping the IPv6 of ocserv"
+	stop
+fi
 
 echo "UserKnownHostsFile ./known-hosts.tmp" >config.tmp
 printf "#\!/bin/sh\n" >echo-admin.tmp
