Added tests for group authentication using passwords and PAM.

diff --git a/tests/test-group-pass b/tests/test-group-pass
--- a/tests/test-group-pass
+++ b/tests/test-group-pass
@@ -24,29 +24,25 @@ PORT=4444
 
 . `dirname $0`/common.sh
 
-echo "Testing PAM backend with username-password... "
+echo "Testing local backend with username-group-password... "
 
-launch_server -d 1 -f -c test-pam.config & PID=$!
+launch_server -d 1 -f -c test-group-pass.config & PID=$!
 wait_server $PID
 
 echo "Connecting to obtain cookie... "
-( echo "test" | openconnect --authgroup test -q localhost:$PORT -u test --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly >/dev/null 2>&1 ) ||
+( echo "test" | openconnect -q localhost:$PORT -u test --authgroup group1 --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly >/dev/null 2>&1 ) ||
 	fail $PID "Could not receive cookie from server"
 
 echo "Connecting to obtain cookie... "
-( echo "test" | openconnect --authgroup DEFAULT -q localhost:$PORT -u test --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly >/dev/null 2>&1 ) ||
+( echo "test" | openconnect -q localhost:$PORT -u test --authgroup group2 --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly >/dev/null 2>&1 ) ||
 	fail $PID "Could not receive cookie from server"
 
 echo "Connecting to obtain cookie... "
-( echo "test" | openconnect --authgroup daemon -q localhost:$PORT -u test --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly >/dev/null 2>&1 ) &&
-	fail $PID "Received cookie when we shouldn't"
+( echo "test" | openconnect -q localhost:$PORT -u test --authgroup group2 --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly >/dev/null 2>&1 ) ||
+	fail $PID "Could not receive cookie from server"
 
-echo "Connecting to obtain cookie with wrong password... "
-( echo "tost" | openconnect --authgroup test -q localhost:$PORT -u test --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly >/dev/null 2>&1 ) &&
-	fail $PID "Received cookie when we shouldn't"
-
-echo "Connecting to obtain cookie with wrong username... "
-( echo "tost" | openconnect --authgroup DEFAULT -q localhost:$PORT -u tost --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly >/dev/null 2>&1 ) &&
+echo "Connecting to obtain cookie with wrong groupname... "
+( echo "test" | openconnect -q localhost:$PORT -u test --authgroup group4 --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly >/dev/null 2>&1 ) &&
 	fail $PID "Received cookie when we shouldn't"
 
 kill $PID
