tests: verify that groupname is read correctly when in kerberos auth

diff --git a/tests/docker-kerberos/myscript b/tests/docker-kerberos/myscript
--- a/tests/docker-kerberos/myscript
+++ b/tests/docker-kerberos/myscript
@@ -6,6 +6,15 @@ if [ "$REASON" != "connect" ];then
 	else
 		echo $STATS_BYTES_IN >/tmp/disconnect/not-ok
 	fi
+elif [ "$REASON" = "connect" ];then
+	rm -f /tmp/disconnect/group-ok
+
+	if test "$GROUPNAME" != "testuser";then
+		echo "Groupname failed: $GROUPNAME" >/tmp/group-not-ok
+		exit 1;
+	else
+		echo "Groupname ok: $GROUPNAME" >/tmp/group-ok
+	fi
 fi
 
 exit 0
diff --git a/tests/kerberos-test b/tests/kerberos-test
--- a/tests/kerberos-test
+++ b/tests/kerberos-test
@@ -104,6 +104,12 @@ if test $? != 0;then
 	ret=1
 fi
 
+check_for_file /tmp/group-ok test_ocserv_kerberos
+if test $? != 0;then
+	echo "Kerberos group name detection test failed"
+	ret=1
+fi
+
 $DOCKER stop test_ocserv_kerberos
 $DOCKER rm test_ocserv_kerberos
 $DOCKER stop test_ocserv_client_kerberos
